{
    "name": "Business Management  ",
    "version": "15.0.0.0.1",
    "depends": ["account", "sale_management", "stock", "purchase", "mrp", "project"],
    "author": "Bizzappdev",
    "category": "Business Management/Business Management",
    "website": "https://github.com/OCA/product-variant",
    "data": [
        "views/sale_order_view.xml",
        "views/account_move_view.xml",
        "views/stock_picking_view.xml",
        "views/purchase_order_view.xml",
        "views/mrp_production_view.xml",
        "views/project_project_view.xml",
        "views/project_task_view.xml",
    ],
    "application": True,
    "installable": True,
    "auto_install": True,
    "license": "AGPL-3",
}
