{
    "name": "School Management",
    "version": "15.0.0.0.1",
    "category": "School Management/School Management",
    "author": "Bizzappdev",
    "summary": "School internal management",
    "website": "https://github.com/OCA/product-variant",
    "depends": ["base", "mail"],
    "data": [
        "security/school_management_security.xml",
        "security/ir.model.access.csv",
        "data/ir_sequence_data.xml",
        "data/school_student_data.xml",
        "data/ir_cron_data.xml",
        "wizard/school_student_wizard_view.xml",
        "views/school_teacher_view.xml",
        "views/school_student_view.xml",
        "views/school_subject_view.xml",
        "views/school_library_view.xml",
        "views/res_config_settings_views.xml",
        "views/school_menu_view.xml",
    ],
    "application": True,
    "installable": True,
    "license": "AGPL-3",
}
