{
    "name": "Placement Cell Management",
    "version": "15.0.0.0.1",
    "category": "Placement Cell Management/Placement Cell Management",
    "author": "Bizzappdev",
    "summary": "Collage Placement Cell Management",
    "website": "https://www.bizzappdev.com",
    "depends": ["base", "mail"],
    "data": [
        "security/ir.model.access.csv",
        "data/mail_template.xml",
        "data/mail_template_data.xml",
        "wizard/placement_apply_view.xml",
        "views/student_views.xml",
        "views/company_views.xml",
        "views/res_config_settings_views.xml",
        "views/placement_staff_views.xml",
        "views/placement_cell_menu.xml",
    ],
    "application": True,
    "installable": True,
    "license": "AGPL-3",
}
