{
    "name": "Placement Cell Management",
    "version": "15.0.0.0.1",
    "category": "Placement Cell Management/Placement Cell Management",
    "author": "Bizzappdev",
    "summary": "Collage Placement Cell Management",
    "website": "https://github.com/OCA/product-variant",
    "depends": ["base", "mail"],
    "data": [
        "security/ir.model.access.csv",
        "views/student_record_view.xml",
        "views/company_record_view.xml",
        "views/res_config_settings_views.xml",
        "views/placement_staff_view.xml",
        "views/placement_cell_menu.xml",
    ],
    "application": True,
    "installable": True,
    "license": "AGPL-3",
}
